export const GET_ALL_MOVIES_SUCCEED = 'GET_ALL_MOVIES_SUCCEED'
export const GET_ALL_MOVIES_ERROR = 'GET_ALL_MOVIES_ERROR'

export const GET_ALL_ACTORS_SUCCEED = 'GET_ALL_ACTORS_SUCCEED'
export const GET_ALL_ACTORS_ERROR = 'GET_ALL_ACTORS_ERROR'

export const GET_DETAIL_ACTOR_SUCCEED= 'GET_DETAIL_ACTOR_SUCCEED'
export const GET_DETAIL_ACTOR_ERROR = 'GET_DETAIL_ACTOR_ERROR'

export const GET_MOVIES_ACTOR_SUCCEED = 'GET_MOVIES_ACTOR_SUCCEED'
export const GET_MOVIES_ACTOR_ERROR = 'GET_MOVIES_ACTOR_ERROR'

export const GET_IMAGE_ACTOR_SUCCEED = 'GET_IMAGE_ACTOR_SUCCEED'
export const GET_IMAGE_ACTOR_ERROR = 'GET_IMAGE_ACTOR_ERROR'

export const GET_DETAIL_MOVIE_SUCCEED = 'GET_DETAIL_MOVIE_SUCCEED'
export const GET_DETAIL_MOVIE_ERROR = 'GET_DETAIL_MOVIE_ERROR'

export const GET_IMAGE_MOVIE_SUCCEED = 'GET_IMAGE_MOVIE_SUCCEED'
export const GET_IMAGE_MOVIE_ERROR = 'GET_IMAGE_MOVIE_ERROR'



